
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FloatingDockNavbar } from "@/components/Pageui/FloatingDockNavbar";
import { NavbarTextFlip } from "@/components/Pageui/NavbarTextFlip";
import CurtainTransition from "@/components/Pageui/Functionality/CurtainTransition";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CurtainTransition>
          <NavbarTextFlip />
          {/* <FloatingDockNavbar /> */}

          {children}
        </CurtainTransition>

      </body>
    </html>
  );
}
